# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Michael Hotard
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Curious individual wanting to affect social change through data and coding. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.mhotard.com" # the base hostname & protocol for your site
twitter_username: gotard
github_username:  mhotard

# Build settings
markdown: kramdown
